FROM nvcr.io/nvidia/pytorch:1.9-py3

RUN apt-get update --fix-missing && \
    apt-get install -y \
      curl \
      python3-virtualenv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY retina/train_requirements.txt requirements.txt
RUN pip install -r requirements.txt

ARG FACE_PIXELIZER=/opt/face_pixelizer
RUN mkdir ${FACE_PIXELIZER}

ARG RETINA=/opt/face_pixeliser/retina
RUN mkdir ${RETINA}
RUN mkdir ${RETINA}/models
COPY retina/train.py ${RETINA}/train.py
COPY retina/models/base_nets.py ${RETINA}/models/base_nets.py
COPY retina/config.yml 
COPY retina/models/custom_retinaface.py ${RETINA}/models/custom_retinaface.py
COPY retina/utils/data_download.py ${FACE_PIXELISER}/data_download.py
