FROM nvcr.io/nvidia/pytorch:21.07-py3
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing && \
    apt-get install -y \
      curl \
      libsm6 \
      libxext6 \
      python3-virtualenv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



COPY retina/train_requirements.txt requirements.txt
RUN pip install opencv-python==4.5.3.56 wget==3.2
RUN pip install -r requirements.txt
RUN rm requirements.txt

# ARG DATA=/home/data_for_face_pixelizer
# RUN mkdir ${DATA}
# COPY data_download.py ${DATA}/data_download.py
# WORKDIR ${DATA}
# RUN python data_download.py -az
#
#RUN mkdir ${RETINA}
#COPY retina/train.py ${RETINA}/train.py
#COPY retina/config.yml ${RETINA}/config.yml
#COPY retina/__init__.py ${RETINA}/__init__.py
#COPY retina/setup.py ${RETINA}/setup.py



#RUN mkdir ${RETINA}/models
#COPY retina/models/base_nets.py ${RETINA}/models/base_nets.py
#COPY retina/models/custom_retinaface.py ${RETINA}/models/custom_retinaface.py

#RUN mkdir ${RETINA}/utils
#COPY retina/utils/utils.py ${RETINA}/utils/utils.py




#RUN pip install -e ${RETINA}
#ARG RETINA=/home/face_pixelizer/retina
#ENV PYTHONPATH "${PYTHONPATH}:${RETINA}"
