batch_size: 64
detection_thres_for_mAP: 0.4
image_size:
  - 512
  - 512
iou_threshold: 0.5
loss_factors:
  cls: 0.1
  ldm: 0.01
  loc: 0.25
lr: 0.001
mAP_epoch_interval: 10
momentum: 0.9
neg_pos_ratio: 3
nms_threshold: 0.3
num_workers: 4
scheduler:
  T_0: 10
  T_mult: 2
seed: 43
variance:
- 0.1
- 0.2
weight_decay: 0.0001
backbone_weights_path: 'weights/MobileNetv1.pth'
# weights_path: 'weights/retinaface_modif_mobilenet_0.25.pth' # remove for training
TRAIN_IMAGE_PATH: "data/WIDER_train/WIDER_train/images"
VAL_IMAGE_PATH: "data/WIDER_val/WIDER_val/images"
TRAIN_LABEL_PATH: "data/WIDER_labels/annotations/train/label.json"
VAL_LABEL_PATH: "data/WIDER_labels/annotations/val/label.json"

checkpoint_callback:
  monitor: val_loss
  verbose: True
  mode: min
  save_top_k: 2
  auto_insert_metric_name: True
  save_weights_only: True
  dirpath: 'artifacts'
  filename: best_val_loss_model

augmentations:
  test_aug:
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      bbox_params: null
      keypoint_params: null
      p: 1
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1
        std:
        - 0.229
        - 0.224
        - 0.225
  train_aug:
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      bbox_params: null
      keypoint_params: null
      p: 1
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        always_apply: false
        brightness_limit: 0.2
        contrast_limit:
        - 0.5
        - 1.5
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
        hue_shift_limit: 20
        p: 0.5
        val_shift_limit: 20
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        gamma_limit:
        - 80
        - 120
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: 512
        p: 1
        width: 512
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1
        std:
        - 0.229
        - 0.224
        - 0.225
  val_aug:
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      bbox_params: null
      keypoint_params: null
      p: 1
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        height: 512
        p: 1
        width: 512
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1
        std:
        - 0.229
        - 0.224
        - 0.225
